### ISSUE TITLE
I Found this

### ISSUE THREAD

**Issue by koolamusic** [Chrismarcel/node-restful-api#1]
So I checked, and I found you, wonderful 
This is Andrew Miracle, John 3:16 Lodge. 

Hope you are doing great

**Comment by Chrismarcel** [comment]
Wow! Wow! Wow! How did you....? Never mind. I'm great bro, how are you
doing? Longest time pal. Hope you're good?

**Comment by koolamusic** [comment]
Sure I am, please share your twitter handle

**Comment by Chrismarcel** [comment]
Here you go bro https://twitter.com/Chrismarcel
